### ISSUE TITLE
How to add a Maybe value

### ISSUE THREAD

**Issue by amitaibu** [andrewthad/yesod-table#7]
I've seen `Table.maybe` but not sure how to use it.

I've got 

``` haskell

getPeopleR :: Handler Html
getPeopleR = do
    people <- runDB $ selectList [] [ Desc UserId ] :: Handler [Entity User]

    let ppl = map entityVal people

    defaultLayout $ do
        setTitle "People List"
        Table.buildBootstrap peopleTable ppl

peopleTable :: Table site User
peopleTable = mempty
    ++ Table.text   "Username"  userIdent
    ++ Table.text   "Email"          userEmail -- This should be a maybe
```

`Email` is a `Maybe` - how would I print it?

**Comment by andrewthad** [comment]
Two options. Even without `Table.maybe`, you can just do this:

```
Table.text   "Email" (fromMaybe "" . userEmail)
```

Or you can use `Table.maybe` to lift the type that the `Table` is parameterized over into a `Maybe`:

```
Table.maybe (Table.text "Email" userEmail)
```

The real advantage of `Table.maybe` (and `Table.maybeWith`) shows up if you have a multi-column table that's going to become part of another `Table`. For example, if you hypothetically had a `Item` type where each `Item` could be associated with either 0 or 1 users, you might have this list after as the result of a left join:

```
itemsWithUsers :: [(Item, Maybe User)]
itemsWithUsers = ...
```

You could then reuse the `peopleTable` that you initially proposed:

```
peopleTable :: Table site User
peopleTable = mconcat
    [ Table.text   "Username"  userIdent
    , Table.text   "Email"          (fromMaybe "" . userEmail)
    ]

itemTable :: Table site Item
itemTable = ...

itemsWithUsersTable :: Table site (Item, Maybe User)
itemsWithUsersTable = mconcat
  [ contramap fst itemTable
  , contramap snd (Table.maybe peopleTable)
  ]
```

**Comment by amitaibu** [comment]
Thanks for the detailed explanation. (Maybe worth adding something similar in the example?)

`Table.maybe (Table.text "Email" userEmail)` doesn't seem to work for me, however `Table.text   "Password"  (fromMaybe "" . userPassword)` does work.

([here](https://github.com/Gizra/yesod-hedley/blob/eba83597fb293cefc1ade5122396ce69c80d878a/Handler/People.hs#L22) the demo app I'm using to experiment)

**Comment by andrewthad** [comment]
Ah, you're right. The type of `Table.maybe (Table.text "Email" userEmail)` would end up being `Table site (Maybe User)` which isn't what you want. I think the only way to work `Table.maybe` into your original example would be pretty convoluted:

```
peopleTable :: Table site User
peopleTable = mempty
    ++ Table.text   "Username"  userIdent
    ++ contramap userEmail (Table.maybe (Table.text "Email" id))
```

But that's just awful, and you'd be way better off with `fromMaybe`.

Also, I realized that my definition of `itemsWithUsersTable` in the previous example I gave was wrong, and I've updated the comment to correct it.

I'll leave this issue open to remind me to add documentation for `Table.maybe`.

**Comment by amitaibu** [comment]
:+1:

**Comment by andrewthad** [comment]
Docs improved with 113118cae4c2e8a1a23fdbf58c82d8694acc5cd2

**Comment by amitaibu** [comment]
Thanks!
